M48
; DRILL file {KiCad 7.0.11-7.0.11~ubuntu22.04.1} date 12.09.2025 (пт) 14:08:15
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-12T14:08:15+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-7.0.11~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X3.46Y5.705
X9.24Y5.705
X16.16Y5.705
X21.94Y5.705
T2
X8.89Y23.622
X16.51Y23.622
T3
X2.54Y10.16
X22.86Y10.16
M30
